alias tm='tmux'
alias jC='cd /home/cuiyunpeng/projects/ai/deeplearning/caffes/py-faster-rcnn'
alias jD='cd /home/cuiyunpeng/projects/ai/deeplearning/darknets/darknet'

alias jN='cd /home/cuiyunpeng/example/test/py/site_pkages/numpy__'
alias jH='cd /home/cuiyunpeng'
alias jK='cd /home/cuiyunpeng/projects'
alias jI='cd /home/cuiyunpeng/Documents/interview'
alias jT='cd /home/cuiyunpeng/example/test'
alias jV='cd /home/cuiyunpeng/.vim/bundle'
alias jL='cd /home/cuiyunpeng/example/test/cpp/syntax'
alias jF='cd /home/cuiyunpeng/example/test/Faster-RCNN_TF-master/lib'
alias jM='cd /home/cuiyunpeng/example/test/tools/systools/terminal-bookmark'
alias jU='cd /home/cuiyunpeng/Documents/To_CuiYunPeng/EHCS_CTRLER_Usr'
alias jA='cd /home/cuiyunpeng/tools/opencv/samples/cpp'
alias jB='cd /home/cuiyunpeng/projects/ai/deeplearning/darknets/alexeyAB/darknet'
alias jY='cd /home/cuiyunpeng/projects/ai/deeplearning/yolo'
alias jO='cd /home/cuiyunpeng/example/test/module/opencv/opencv'
